



<!DOCTYPE html>
<html lang="en" class="">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    
    
    <title>makinacorpus/Leaflet.Spin · GitHub</title>
    <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub">
    <link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-114.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-144.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144.png">
    <meta property="fb:app_id" content="1401488693436528">

      <meta content="@github" name="twitter:site" /><meta content="summary" name="twitter:card" /><meta content="makinacorpus/Leaflet.Spin" name="twitter:title" /><meta content="Leaflet.Spin - Show a spinner on the map using Spin.js" name="twitter:description" /><meta content="https://avatars2.githubusercontent.com/u/546696?v=2&amp;s=400" name="twitter:image:src" />
<meta content="GitHub" property="og:site_name" /><meta content="object" property="og:type" /><meta content="https://avatars2.githubusercontent.com/u/546696?v=2&amp;s=400" property="og:image" /><meta content="makinacorpus/Leaflet.Spin" property="og:title" /><meta content="https://github.com/makinacorpus/Leaflet.Spin" property="og:url" /><meta content="Leaflet.Spin - Show a spinner on the map using Spin.js" property="og:description" />

      <meta name="browser-stats-url" content="/_stats">
    <link rel="assets" href="https://assets-cdn.github.com/">
    <link rel="conduit-xhr" href="https://ghconduit.com:25035">
    
    <meta name="pjax-timeout" content="1000">
    

    <meta name="msapplication-TileImage" content="/windows-tile.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="selected-link" value="repo_source" data-pjax-transient>
      <meta name="google-analytics" content="UA-3769691-2">

    <meta content="collector.githubapp.com" name="octolytics-host" /><meta content="collector-cdn.github.com" name="octolytics-script-host" /><meta content="github" name="octolytics-app-id" /><meta content="94FB16D5:5F97:1B6747A:545B90C4" name="octolytics-dimension-request_id" />
    
    <meta content="Rails, view, files#disambiguate" name="analytics-event" />

    
    
    <link rel="icon" type="image/x-icon" href="https://assets-cdn.github.com/favicon.ico">


    <meta content="authenticity_token" name="csrf-param" />
<meta content="kgbuSLzYhQHCmvZ5N6RHRJDtANGTYuuePxkcwce9F9U3sXsP5tH1KZoXyWO0iy1GUYrDsO/qvy9iopgkCY3u0A==" name="csrf-token" />

    <link href="https://assets-cdn.github.com/assets/github-a8245103ff0c62d80a5873f3945cba7d725981a119c390859dc4e9f3ecc6701b.css" media="all" rel="stylesheet" type="text/css" />
    <link href="https://assets-cdn.github.com/assets/github2-b25a40af1beac9123b7e106ddbaa3acf8bc8c6e54030de383e0c0c5574c37dd4.css" media="all" rel="stylesheet" type="text/css" />
    
    


    <meta http-equiv="x-pjax-version" content="dc3f4b1a5a114866f80e8d81c968b3d0">

      
  <meta name="description" content="Leaflet.Spin - Show a spinner on the map using Spin.js">
  <meta name="go-import" content="github.com/makinacorpus/Leaflet.Spin git https://github.com/makinacorpus/Leaflet.Spin.git">

  <meta content="546696" name="octolytics-dimension-user_id" /><meta content="makinacorpus" name="octolytics-dimension-user_login" /><meta content="8557579" name="octolytics-dimension-repository_id" /><meta content="makinacorpus/Leaflet.Spin" name="octolytics-dimension-repository_nwo" /><meta content="true" name="octolytics-dimension-repository_public" /><meta content="false" name="octolytics-dimension-repository_is_fork" /><meta content="8557579" name="octolytics-dimension-repository_network_root_id" /><meta content="makinacorpus/Leaflet.Spin" name="octolytics-dimension-repository_network_root_nwo" />
  <link href="https://github.com/makinacorpus/Leaflet.Spin/commits/master.atom" rel="alternate" title="Recent Commits to Leaflet.Spin:master" type="application/atom+xml">

  </head>


  <body class="logged_out  env-production  vis-public">
    <a href="#start-of-content" tabindex="1" class="accessibility-aid js-skip-to-content">Skip to content</a>
    <div class="wrapper">
      
      
      
      


      
      <div class="header header-logged-out" role="banner">
  <div class="container clearfix">

    <a class="header-logo-wordmark" href="https://github.com/" ga-data-click="(Logged out) Header, go to homepage, icon:logo-wordmark">
      <span class="mega-octicon octicon-logo-github"></span>
    </a>

    <div class="header-actions" role="navigation">
        <a class="button primary" href="/join" data-ga-click="(Logged out) Header, clicked Sign up, text:sign-up">Sign up</a>
      <a class="button signin" href="/login?return_to=%2Fmakinacorpus%2FLeaflet.Spin" data-ga-click="(Logged out) Header, clicked Sign in, text:sign-in">Sign in</a>
    </div>

    <div class="site-search repo-scope js-site-search" role="search">
      <form accept-charset="UTF-8" action="/makinacorpus/Leaflet.Spin/search" class="js-site-search-form" data-global-search-url="/search" data-repo-search-url="/makinacorpus/Leaflet.Spin/search" method="get"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
  <input type="text"
    class="js-site-search-field is-clearable"
    data-hotkey="s"
    name="q"
    placeholder="Search"
    data-global-scope-placeholder="Search GitHub"
    data-repo-scope-placeholder="Search"
    tabindex="1"
    autocapitalize="off">
  <div class="scope-badge">This repository</div>
</form>
    </div>

      <ul class="header-nav left" role="navigation">
          <li class="header-nav-item">
            <a class="header-nav-link" href="/explore" data-ga-click="(Logged out) Header, go to explore, text:explore">Explore</a>
          </li>
          <li class="header-nav-item">
            <a class="header-nav-link" href="/features" data-ga-click="(Logged out) Header, go to features, text:features">Features</a>
          </li>
          <li class="header-nav-item">
            <a class="header-nav-link" href="https://enterprise.github.com/" data-ga-click="(Logged out) Header, go to enterprise, text:enterprise">Enterprise</a>
          </li>
          <li class="header-nav-item">
            <a class="header-nav-link" href="/blog" data-ga-click="(Logged out) Header, go to blog, text:blog">Blog</a>
          </li>
      </ul>

  </div>
</div>



      <div id="start-of-content" class="accessibility-aid"></div>
          <div class="site" itemscope itemtype="http://schema.org/WebPage">
    <div id="js-flash-container">
      
    </div>
    <div class="pagehead repohead instapaper_ignore readability-menu">
      <div class="container">
        
<ul class="pagehead-actions">


  <li>
      <a href="/login?return_to=%2Fmakinacorpus%2FLeaflet.Spin"
    class="minibutton with-count star-button tooltipped tooltipped-n"
    aria-label="You must be signed in to star a repository" rel="nofollow">
    <span class="octicon octicon-star"></span>
    Star
  </a>

    <a class="social-count js-social-count" href="/makinacorpus/Leaflet.Spin/stargazers">
      29
    </a>

  </li>

    <li>
      <a href="/login?return_to=%2Fmakinacorpus%2FLeaflet.Spin"
        class="minibutton with-count js-toggler-target fork-button tooltipped tooltipped-n"
        aria-label="You must be signed in to fork a repository" rel="nofollow">
        <span class="octicon octicon-repo-forked"></span>
        Fork
      </a>
      <a href="/makinacorpus/Leaflet.Spin/network" class="social-count">
        8
      </a>
    </li>
</ul>

        <h1 itemscope itemtype="http://data-vocabulary.org/Breadcrumb" class="entry-title public">
          <span class="mega-octicon octicon-repo"></span>
          <span class="author"><a href="/makinacorpus" class="url fn" itemprop="url" rel="author"><span itemprop="title">makinacorpus</span></a></span><!--
       --><span class="path-divider">/</span><!--
       --><strong><a href="/makinacorpus/Leaflet.Spin" class="js-current-repository js-repo-home-link" data-pjax-container-selector="#js-repo-pjax-container">Leaflet.Spin</a></strong>

          <span class="page-context-loader">
            <img alt="" height="16" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" />
          </span>

        </h1>
      </div><!-- /.container -->
    </div><!-- /.repohead -->

    <div class="container">
      <div class="repository-with-sidebar repo-container new-discussion-timeline with-full-navigation ">
        <div class="repository-sidebar clearfix">
            
<nav class="sunken-menu repo-nav js-repo-nav js-sidenav-container-pjax js-octicon-loaders" role="navigation" data-issue-count-url="/makinacorpus/Leaflet.Spin/issues/counts" data-pjax-container-selector="#js-repo-pjax-container">
  <ul class="sunken-menu-group">
    <li class="tooltipped tooltipped-w" aria-label="Code">
      <a href="/makinacorpus/Leaflet.Spin" aria-label="Code" class="selected js-selected-navigation-item sunken-menu-item" data-hotkey="g c" data-pjax="true" data-selected-links="repo_source repo_downloads repo_commits repo_releases repo_tags repo_branches /makinacorpus/Leaflet.Spin">
        <span class="octicon octicon-code"></span> <span class="full-word">Code</span>
        <img alt="" class="mini-loader" height="16" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" />
</a>    </li>

      <li class="tooltipped tooltipped-w" aria-label="Issues">
        <a href="/makinacorpus/Leaflet.Spin/issues" aria-label="Issues" class="js-selected-navigation-item sunken-menu-item js-disable-pjax" data-hotkey="g i" data-selected-links="repo_issues repo_labels repo_milestones /makinacorpus/Leaflet.Spin/issues">
          <span class="octicon octicon-issue-opened"></span> <span class="full-word">Issues</span>
          <span class="js-issue-replace-counter"></span>
          <img alt="" class="mini-loader" height="16" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" />
</a>      </li>

    <li class="tooltipped tooltipped-w" aria-label="Pull Requests">
      <a href="/makinacorpus/Leaflet.Spin/pulls" aria-label="Pull Requests" class="js-selected-navigation-item sunken-menu-item js-disable-pjax" data-hotkey="g p" data-selected-links="repo_pulls /makinacorpus/Leaflet.Spin/pulls">
          <span class="octicon octicon-git-pull-request"></span> <span class="full-word">Pull Requests</span>
          <span class="js-pull-replace-counter"></span>
          <img alt="" class="mini-loader" height="16" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" />
</a>    </li>


  </ul>
  <div class="sunken-menu-separator"></div>
  <ul class="sunken-menu-group">

    <li class="tooltipped tooltipped-w" aria-label="Pulse">
      <a href="/makinacorpus/Leaflet.Spin/pulse/weekly" aria-label="Pulse" class="js-selected-navigation-item sunken-menu-item" data-pjax="true" data-selected-links="pulse /makinacorpus/Leaflet.Spin/pulse/weekly">
        <span class="octicon octicon-pulse"></span> <span class="full-word">Pulse</span>
        <img alt="" class="mini-loader" height="16" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" />
</a>    </li>

    <li class="tooltipped tooltipped-w" aria-label="Graphs">
      <a href="/makinacorpus/Leaflet.Spin/graphs" aria-label="Graphs" class="js-selected-navigation-item sunken-menu-item" data-pjax="true" data-selected-links="repo_graphs repo_contributors /makinacorpus/Leaflet.Spin/graphs">
        <span class="octicon octicon-graph"></span> <span class="full-word">Graphs</span>
        <img alt="" class="mini-loader" height="16" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" />
</a>    </li>
  </ul>


</nav>

              <div class="only-with-full-nav">
                
  
<div class="clone-url open"
  data-protocol-type="http"
  data-url="/users/set_protocol?protocol_selector=http&amp;protocol_type=clone">
  <h3><span class="text-emphasized">HTTPS</span> clone URL</h3>
  <div class="input-group">
    <input type="text" class="input-mini input-monospace js-url-field"
           value="https://github.com/makinacorpus/Leaflet.Spin.git" readonly="readonly">
    <span class="input-group-button">
      <button aria-label="Copy to clipboard" class="js-zeroclipboard minibutton zeroclipboard-button" data-clipboard-text="https://github.com/makinacorpus/Leaflet.Spin.git" data-copied-hint="Copied!" type="button"><span class="octicon octicon-clippy"></span></button>
    </span>
  </div>
</div>

  
<div class="clone-url "
  data-protocol-type="subversion"
  data-url="/users/set_protocol?protocol_selector=subversion&amp;protocol_type=clone">
  <h3><span class="text-emphasized">Subversion</span> checkout URL</h3>
  <div class="input-group">
    <input type="text" class="input-mini input-monospace js-url-field"
           value="https://github.com/makinacorpus/Leaflet.Spin" readonly="readonly">
    <span class="input-group-button">
      <button aria-label="Copy to clipboard" class="js-zeroclipboard minibutton zeroclipboard-button" data-clipboard-text="https://github.com/makinacorpus/Leaflet.Spin" data-copied-hint="Copied!" type="button"><span class="octicon octicon-clippy"></span></button>
    </span>
  </div>
</div>


<p class="clone-options">You can clone with
      <a href="#" class="js-clone-selector" data-protocol="http">HTTPS</a>
      or <a href="#" class="js-clone-selector" data-protocol="subversion">Subversion</a>.
  <a href="https://help.github.com/articles/which-remote-url-should-i-use" class="help tooltipped tooltipped-n" aria-label="Get help on which URL is right for you.">
    <span class="octicon octicon-question"></span>
  </a>
</p>



                <a href="/makinacorpus/Leaflet.Spin/archive/master.zip"
                   class="minibutton sidebar-button"
                   aria-label="Download the contents of makinacorpus/Leaflet.Spin as a zip file"
                   title="Download the contents of makinacorpus/Leaflet.Spin as a zip file"
                   rel="nofollow">
                  <span class="octicon octicon-cloud-download"></span>
                  Download ZIP
                </a>
              </div>
        </div><!-- /.repository-sidebar -->

        <div id="js-repo-pjax-container" class="repository-content context-loader-container" data-pjax-container>
          
<span id="js-show-full-navigation"></span>

<div class="repository-meta js-details-container ">
    <div class="repository-description">
      <p>Show a spinner on the map using Spin.js</p>
    </div>

    <div class="repository-website">
      <p><a href="http://makinacorpus.github.io/Leaflet.Spin/" rel="nofollow">http://makinacorpus.github.io/Leaflet.Spin/</a></p>
    </div>


</div>

<div class="overall-summary overall-summary-bottomless">

  <div class="stats-switcher-viewport js-stats-switcher-viewport">
    <div class="stats-switcher-wrapper">
    <ul class="numbers-summary">
      <li class="commits">
        <a data-pjax href="/makinacorpus/Leaflet.Spin/commits/master">
            <span class="octicon octicon-history"></span>
            <span class="num text-emphasized">
              19
            </span>
            commits
        </a>
      </li>
      <li>
        <a data-pjax href="/makinacorpus/Leaflet.Spin/branches">
          <span class="octicon octicon-git-branch"></span>
          <span class="num text-emphasized">
            2
          </span>
          branches
        </a>
      </li>

      <li>
        <a data-pjax href="/makinacorpus/Leaflet.Spin/releases">
          <span class="octicon octicon-tag"></span>
          <span class="num text-emphasized">
            0
          </span>
          releases
        </a>
      </li>

      <li>
        
  <a href="/makinacorpus/Leaflet.Spin/graphs/contributors">
    <span class="octicon octicon-organization"></span>
    <span class="num text-emphasized">
      2
    </span>
    contributors
  </a>
      </li>
    </ul>

      <div class="repository-lang-stats">
        <ol class="repository-lang-stats-numbers">
          <li>
              <a href="/makinacorpus/Leaflet.Spin/search?l=javascript">
                <span class="color-block language-color" style="background-color:#f1e05a;"></span>
                <span class="lang">JavaScript</span>
                <span class="percent">100%</span>
              </a>
          </li>
        </ol>
      </div>
    </div>
  </div>

</div>

  <div class="tooltipped tooltipped-s" aria-label="Show language statistics">
    <a href="#"
     class="repository-lang-stats-graph js-toggle-lang-stats"
     style="background-color:#f1e05a">
  <span class="language-color" style="width:100%; background-color:#f1e05a;" itemprop="keywords">JavaScript</span>
    </a>
  </div>

<include-fragment src="/makinacorpus/Leaflet.Spin/show_partial?partial=recently_touched_branches_list"></include-fragment>

<div class="file-navigation in-mid-page">
  <a href="/makinacorpus/Leaflet.Spin/find/master"
        class="js-show-file-finder minibutton empty-icon tooltipped tooltipped-s right"
        data-pjax
        data-hotkey="t"
        aria-label="Quickly jump between files">
    <span class="octicon octicon-list-unordered"></span>
  </a>
    <a href="/makinacorpus/Leaflet.Spin/compare" aria-label="Compare, review, create a pull request" class="minibutton primary tooltipped tooltipped-s left compare-button" aria-label="Compare &amp; review" data-pjax>
      <span class="octicon octicon-git-compare"></span>
    </a>

  
<div class="select-menu js-menu-container js-select-menu left">
  <span class="minibutton select-menu-button js-menu-target css-truncate" data-hotkey="w"
    data-master-branch="master"
    data-ref="master"
    title="master"
    role="button" aria-label="Switch branches or tags" tabindex="0" aria-haspopup="true">
    <span class="octicon octicon-git-branch"></span>
    <i>branch:</i>
    <span class="js-select-button css-truncate-target">master</span>
  </span>

  <div class="select-menu-modal-holder js-menu-content js-navigation-container" data-pjax aria-hidden="true">

    <div class="select-menu-modal">
      <div class="select-menu-header">
        <span class="select-menu-title">Switch branches/tags</span>
        <span class="octicon octicon-x js-menu-close" role="button" aria-label="Close"></span>
      </div> <!-- /.select-menu-header -->

      <div class="select-menu-filters">
        <div class="select-menu-text-filter">
          <input type="text" aria-label="Filter branches/tags" id="context-commitish-filter-field" class="js-filterable-field js-navigation-enable" placeholder="Filter branches/tags">
        </div>
        <div class="select-menu-tabs">
          <ul>
            <li class="select-menu-tab">
              <a href="#" data-tab-filter="branches" class="js-select-menu-tab">Branches</a>
            </li>
            <li class="select-menu-tab">
              <a href="#" data-tab-filter="tags" class="js-select-menu-tab">Tags</a>
            </li>
          </ul>
        </div><!-- /.select-menu-tabs -->
      </div><!-- /.select-menu-filters -->

      <div class="select-menu-list select-menu-tab-bucket js-select-menu-tab-bucket" data-tab-filter="branches">

        <div data-filterable-for="context-commitish-filter-field" data-filterable-type="substring">


            <div class="select-menu-item js-navigation-item ">
              <span class="select-menu-item-icon octicon octicon-check"></span>
              <a href="/makinacorpus/Leaflet.Spin/tree/gh-pages"
                 data-name="gh-pages"
                 data-skip-pjax="true"
                 rel="nofollow"
                 class="js-navigation-open select-menu-item-text css-truncate-target"
                 title="gh-pages">gh-pages</a>
            </div> <!-- /.select-menu-item -->
            <div class="select-menu-item js-navigation-item selected">
              <span class="select-menu-item-icon octicon octicon-check"></span>
              <a href="/makinacorpus/Leaflet.Spin/tree/master"
                 data-name="master"
                 data-skip-pjax="true"
                 rel="nofollow"
                 class="js-navigation-open select-menu-item-text css-truncate-target"
                 title="master">master</a>
            </div> <!-- /.select-menu-item -->
        </div>

          <div class="select-menu-no-results">Nothing to show</div>
      </div> <!-- /.select-menu-list -->

      <div class="select-menu-list select-menu-tab-bucket js-select-menu-tab-bucket" data-tab-filter="tags">
        <div data-filterable-for="context-commitish-filter-field" data-filterable-type="substring">


        </div>

        <div class="select-menu-no-results">Nothing to show</div>
      </div> <!-- /.select-menu-list -->

    </div> <!-- /.select-menu-modal -->
  </div> <!-- /.select-menu-modal-holder -->
</div> <!-- /.select-menu -->



  <div class="breadcrumb"><span class='repo-root js-repo-root'><span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/makinacorpus/Leaflet.Spin" class="" data-branch="master" data-direction="back" data-pjax="true" itemscope="url"><span itemprop="title">Leaflet.Spin</span></a></span></span><span class="separator"> / </span><form action="/login?return_to=%2Fmakinacorpus%2FLeaflet.Spin" aria-label="Sign in to make or propose changes" class="js-new-blob-form tooltipped tooltipped-e new-file-link" method="post"><span aria-label="Sign in to make or propose changes" class="js-new-blob-submit octicon octicon-plus" data-test-id="create-new-git-file" role="button"></span></form></div>
</div>



  
  <div class="commit commit-tease js-details-container" >
    <p class="commit-title ">
        <a href="/makinacorpus/Leaflet.Spin/commit/494c0596be353b83b35de07971680e2d2f441bca" class="message" data-pjax="true" title="Allow to pass Spin.js options at first spin call (fixes #6)">Allow to pass Spin.js options at first spin call (fixes</a> <a href="https://github.com/makinacorpus/Leaflet.Spin/issues/6" class="issue-link" title="Position of the Spinner">#6</a><a href="/makinacorpus/Leaflet.Spin/commit/494c0596be353b83b35de07971680e2d2f441bca" class="message" data-pjax="true" title="Allow to pass Spin.js options at first spin call (fixes #6)">)</a>
        
    </p>
    <div class="commit-meta">
      <button aria-label="Copy SHA" class="js-zeroclipboard zeroclipboard-link" data-clipboard-text="494c0596be353b83b35de07971680e2d2f441bca" data-copied-hint="Copied!" type="button"><span class="octicon octicon-clippy"></span></button>
      <a href="/makinacorpus/Leaflet.Spin/commit/494c0596be353b83b35de07971680e2d2f441bca" class="sha-block" data-pjax>latest commit <span class="sha">494c0596be</span></a>

      <div class="authorship">
        <img alt="Mathieu Leplatre" class="avatar" data-user="546692" height="20" src="https://avatars0.githubusercontent.com/u/546692?v=2&amp;s=40" width="20" />
        <span class="author-name"><a href="/leplatrem" rel="contributor">leplatrem</a></span>
        authored <time class="updated" datetime="2013-08-06T09:29:05Z" is="relative-time">Aug 6, 2013</time>

      </div>
    </div>
  </div>

  <div class="file-wrap">
    <table class="files" data-pjax>

      <tbody class=""
  data-url="/makinacorpus/Leaflet.Spin/file-list/master"
  data-deferred-content-error="Failed to load latest commit information.">

    <tr>
      <td class="icon">
        <span class="octicon octicon-file-text"></span>
        <img alt="" class="spinner" height="16" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" />
      </td>
      <td class="content">
        <span class="css-truncate css-truncate-target"><a href="/makinacorpus/Leaflet.Spin/blob/master/LICENSE" class="js-directory-link" id="9879d6db96fd29134fc802214163b95a-ed5f61ef76e76b36fb2b914026a799391e9c0e26" title="LICENSE">LICENSE</a></span>
      </td>
      <td class="message">
        <span class="css-truncate css-truncate-target ">
          <a href="/makinacorpus/Leaflet.Spin/commit/07746d1a9af00209aa155f6bf85f9ab4ebe40749" class="message" data-pjax="true" title="Add Licence">Add Licence</a>
        </span>
      </td>
      <td class="age">
        <span class="css-truncate css-truncate-target"><time datetime="2013-03-06T10:27:05Z" is="time-ago">Mar 6, 2013</time></span>
      </td>
    </tr>
    <tr>
      <td class="icon">
        <span class="octicon octicon-file-text"></span>
        <img alt="" class="spinner" height="16" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" />
      </td>
      <td class="content">
        <span class="css-truncate css-truncate-target"><a href="/makinacorpus/Leaflet.Spin/blob/master/README.md" class="js-directory-link" id="04c6e90faac2675aa89e2176d2eec7d8-e36092d7467aea9ec7ea1f2088fe3322d2c7f40c" title="README.md">README.md</a></span>
      </td>
      <td class="message">
        <span class="css-truncate css-truncate-target ">
          <a href="/makinacorpus/Leaflet.Spin/commit/494c0596be353b83b35de07971680e2d2f441bca" class="message" data-pjax="true" title="Allow to pass Spin.js options at first spin call (fixes #6)">Allow to pass Spin.js options at first spin call (fixes</a> <a href="https://github.com/makinacorpus/Leaflet.Spin/issues/6" class="issue-link" title="Position of the Spinner">#6</a><a href="/makinacorpus/Leaflet.Spin/commit/494c0596be353b83b35de07971680e2d2f441bca" class="message" data-pjax="true" title="Allow to pass Spin.js options at first spin call (fixes #6)">)</a>
        </span>
      </td>
      <td class="age">
        <span class="css-truncate css-truncate-target"><time datetime="2013-08-06T09:29:05Z" is="time-ago">Aug 6, 2013</time></span>
      </td>
    </tr>
    <tr>
      <td class="icon">
        <span class="octicon octicon-file-text"></span>
        <img alt="" class="spinner" height="16" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" />
      </td>
      <td class="content">
        <span class="css-truncate css-truncate-target"><a href="/makinacorpus/Leaflet.Spin/blob/master/leaflet.spin.js" class="js-directory-link" id="d864b43772969ebe02de9fbd4476b0d9-cee5d6aa696c988f949857be42c6067f29117315" title="leaflet.spin.js">leaflet.spin.js</a></span>
      </td>
      <td class="message">
        <span class="css-truncate css-truncate-target ">
          <a href="/makinacorpus/Leaflet.Spin/commit/494c0596be353b83b35de07971680e2d2f441bca" class="message" data-pjax="true" title="Allow to pass Spin.js options at first spin call (fixes #6)">Allow to pass Spin.js options at first spin call (fixes</a> <a href="https://github.com/makinacorpus/Leaflet.Spin/issues/6" class="issue-link" title="Position of the Spinner">#6</a><a href="/makinacorpus/Leaflet.Spin/commit/494c0596be353b83b35de07971680e2d2f441bca" class="message" data-pjax="true" title="Allow to pass Spin.js options at first spin call (fixes #6)">)</a>
        </span>
      </td>
      <td class="age">
        <span class="css-truncate css-truncate-target"><time datetime="2013-08-06T09:29:05Z" is="time-ago">Aug 6, 2013</time></span>
      </td>
    </tr>
</tbody>

    </table>
  </div>


  <div id="readme" class="boxed-group flush clearfix announce instapaper_body md">
    <h3>
      <span class="octicon octicon-book"></span>
      README.md
    </h3>

    <article class="markdown-body entry-content" itemprop="mainContentOfPage"><h1>
<a id="user-content-leafletspin" class="anchor" href="#leafletspin" aria-hidden="true"><span class="octicon octicon-link"></span></a>Leaflet.Spin</h1>

<p>Shows a nice spin cursor on the map.</p>

<p>Requires <a href="http://fgnass.github.com/spin.js/">Spin.js</a>.</p>

<p>See <a href="http://makinacorpus.github.io/Leaflet.Spin/">online demo</a>.</p>

<h2>
<a id="user-content-usage" class="anchor" href="#usage" aria-hidden="true"><span class="octicon octicon-link"></span></a>Usage</h2>

<h3>
<a id="user-content-manually" class="anchor" href="#manually" aria-hidden="true"><span class="octicon octicon-link"></span></a>Manually</h3>

<div class="highlight highlight-javascript"><pre>map.spin(<span class="kc">true</span>);  <span class="c1">// on</span>
...
map.spin(<span class="kc">false</span>);  <span class="c1">// off</span></pre></div>

<h3>
<a id="user-content-spinjs-options" class="anchor" href="#spinjs-options" aria-hidden="true"><span class="octicon octicon-link"></span></a>Spin.js options</h3>

<p>You can control apparence of wheel by passing options on first <code>spin()</code> call.</p>

<div class="highlight highlight-javascript"><pre>map.spin(<span class="kc">true</span>, {lines: <span class="m">13</span>, <span class="no">length</span>: <span class="m">40</span>});</pre></div>

<p><a href="http://fgnass.github.io/spin.js/">More details on available options</a>...</p>

<h3>
<a id="user-content-with-ajax--jquery" class="anchor" href="#with-ajax--jquery" aria-hidden="true"><span class="octicon octicon-link"></span></a>With AJAX / JQuery</h3>

<pre><code>    map.spin(true);
    $.ajax({url: 'http://server/api/'})
     .done(function() {
        map.spin(false);
      })
     .error(function () {
        map.spin(false);
      });

</code></pre>

<p>Using events:</p>

<pre><code>    var layer = L.geoJson(null).addTo(map);

    layer.fire('data:loading');
    $.getJSON('http://server/path.geojson', function (data) {
        layer.fire('data:loaded');
        layer.addData(data);
    });

</code></pre>

<h3>
<a id="user-content-with-leafletajax" class="anchor" href="#with-leafletajax" aria-hidden="true"><span class="octicon octicon-link"></span></a>With <a href="https://github.com/calvinmetcalf/leaflet-ajax/">Leaflet.AJAX</a>
</h3>

<pre><code>
    var layer = L.geoJson.ajax();
    layer.addUrl('http://server/path.geojson');

</code></pre>

<h2>
<a id="user-content-authors" class="anchor" href="#authors" aria-hidden="true"><span class="octicon octicon-link"></span></a>Authors</h2>

<p><a href="http://makinacorpus.com"><img src="https://camo.githubusercontent.com/c5859727cdfb8bb52c1d726d502c052a0e6d9383/687474703a2f2f6465706f742e6d616b696e612d636f727075732e6f72672f7075626c69632f6c6f676f2e676966" alt="Makina Corpus" data-canonical-src="http://depot.makina-corpus.org/public/logo.gif" style="max-width:100%;"></a></p>
</article>
  </div>


        </div>

      </div><!-- /.repo-container -->
      <div class="modal-backdrop"></div>
    </div><!-- /.container -->
  </div><!-- /.site -->


    </div><!-- /.wrapper -->

      <div class="container">
  <div class="site-footer" role="contentinfo">
    <ul class="site-footer-links right">
      <li><a href="https://status.github.com/">Status</a></li>
      <li><a href="https://developer.github.com">API</a></li>
      <li><a href="http://training.github.com">Training</a></li>
      <li><a href="http://shop.github.com">Shop</a></li>
      <li><a href="/blog">Blog</a></li>
      <li><a href="/about">About</a></li>

    </ul>

    <a href="/" aria-label="Homepage">
      <span class="mega-octicon octicon-mark-github" title="GitHub"></span>
    </a>

    <ul class="site-footer-links">
      <li>&copy; 2014 <span title="0.03088s from github-fe123-cp1-prd.iad.github.net">GitHub</span>, Inc.</li>
        <li><a href="/site/terms">Terms</a></li>
        <li><a href="/site/privacy">Privacy</a></li>
        <li><a href="/security">Security</a></li>
        <li><a href="/contact">Contact</a></li>
    </ul>
  </div><!-- /.site-footer -->
</div><!-- /.container -->


    <div class="fullscreen-overlay js-fullscreen-overlay" id="fullscreen_overlay">
  <div class="fullscreen-container js-suggester-container">
    <div class="textarea-wrap">
      <textarea name="fullscreen-contents" id="fullscreen-contents" class="fullscreen-contents js-fullscreen-contents js-suggester-field" placeholder=""></textarea>
    </div>
  </div>
  <div class="fullscreen-sidebar">
    <a href="#" class="exit-fullscreen js-exit-fullscreen tooltipped tooltipped-w" aria-label="Exit Zen Mode">
      <span class="mega-octicon octicon-screen-normal"></span>
    </a>
    <a href="#" class="theme-switcher js-theme-switcher tooltipped tooltipped-w"
      aria-label="Switch themes">
      <span class="octicon octicon-color-mode"></span>
    </a>
  </div>
</div>



    <div id="ajax-error-message" class="flash flash-error">
      <span class="octicon octicon-alert"></span>
      <a href="#" class="octicon octicon-x flash-close js-ajax-error-dismiss" aria-label="Dismiss error"></a>
      Something went wrong with that request. Please try again.
    </div>


      <script crossorigin="anonymous" src="https://assets-cdn.github.com/assets/frameworks-fe1dc1d9b25d6a0cda010576a3c4be01906c9fd2ac07462042e5fceda326d50c.js" type="text/javascript"></script>
      <script async="async" crossorigin="anonymous" src="https://assets-cdn.github.com/assets/github-1fd51652e44692eb9e367097c2c5d7188a1e1d6a04c0e177d2800325dbadae57.js" type="text/javascript"></script>
      
      
  </body>
</html>

